services:
  db:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"

  app: 
    image: shitty_app:1.0
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - DB_HOST=db # en supposant que vous avez bien déclaré votre conteneur MySQL avec le nom "db"
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=shitty_app_db
      - DB_PORT=3306
      - PORT=3000    

volumes:
  db_data:
   - "/my/own/datadir:/var/lib/mysql"